source "https://rubygems.org"

gem "addressable"
gem "middleman", "~> 4.1.0"
gem "middleman-autoprefixer"
gem "middleman-blog"
gem "middleman-livereload"
gem "middleman-minify-html"
gem "middleman-syntax"
gem "middleman-gh-pages", ">= 0.0.3"
gem "redcarpet"
gem "pry"
