source "https://rubygems.org"

gem "addressable"
gem "middleman", "~> 4.1.11"
gem "middleman-autoprefixer", ">= 2.7.1"
gem "middleman-blog", ">= 4.0.2"
gem "middleman-livereload", ">= 3.4.7"
gem "middleman-minify-html"
gem "middleman-syntax", ">= 3.2.0"
gem "middleman-gh-pages"
gem "redcarpet"
gem "pry"
